export enum ActionTypes {
  ADD_MOVIE = 'ADD_MOVIE',
  DELETE_MOVIE = 'DELETE_MOVIE',
  UPDATE_MOVIE = 'UPDATE_MOVIE',
  LOAD_MOVIES = 'LOAD_MOVIES',
  SET_MOVIES = 'SET_MOVIES',
  GET_MOVIE = 'GET_MOVIE',
  SET_MOVIE = 'SET_MOVIE',
  SET_ALERT = 'ADD_ALERT',
  SET_LOADING = 'SET-LOADING'
}
